name: workflow issues
on: issues
jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            - name: issue
              run:  |
                echo "${{toJson(github.event.issue.title)}}"
                echo "${{toJson(github.event.issue.body)}}"